export const routes = {
    auth: {
        login: "/auth/login",
        register: "/auth/register-company",
        verify: "/auth/verify",
        acceptInvite: "/auth/accept-invite",
        logout: "/auth/logout",
        forgotPassword: "/auth/forgot-password",
        resetPassword: "/auth/finish-reset-password",
        refreshToken: "/auth/refresh-tokens",
        verifyOnboardingToken: "/auth/verify-onboarding-token",
        verifyResetToken: "/auth/verify-reset-token",
        setupPassword: "/client/users/setup-password",
        verifyRegistration: "/auth/verify-registration",
        selectOrganization: "/auth/select-organization",
        registerInvitedUser: "/auth/register-invited-user",
        resendOtp: "/auth/resend-otp",
    },
    organization: {
        index: "/client/organizations",
        me: "/client/organizations/me",
        internalCreate: "/internal/organizations",
        internalDetail: (id: string) => `/internal/organizations/${id}`, // Used for DELETE (disable)
        internalEnable: (id: string) => `/internal/organizations/${id}/enable`,
        internalResendInvite: (id: string) => `/internal/organizations/${id}/resend-invite`,
        bulkInvite: (id: string) => `/client/organizations/${id}/bulk-invite`,
        members: (id: string) => `/client/organizations/${id}/members`,
        member: (id: string, memberId: string) => `/client/organizations/${id}/members/${memberId}`,
        invitations: (id: string) => `/client/organizations/${id}/invitations`,
        invitation: (id: string, invitationToken: string) => `/client/organizations/${id}/invitations/${invitationToken}`,
        resendInvitationByToken: (id: string, invitationToken: string) => `/client/organizations/${id}/invitations/${invitationToken}/resend`,
        hubstaffAuth: (id: string) => `/client/organizations/${id}/hubstaff/auth`,
        hubstaffExchangeToken: (id: string) => `/client/organizations/${id}/hubstaff/exchange-token`,
        hubstaffDisconnect: (id: string) => `/client/organizations/${id}/hubstaff/disconnect`,
        hubstaffProjects: (id: string) => `/client/organizations/${id}/hubstaff/projects`,
        acceptInvitation: (id: string) => `/client/organizations/${id}/accept-invitation`,
        rejectInvitation: (id: string) => `/client/organizations/${id}/reject-invitation`,
        pTOPolicy: (id: string) => `/client/organizations/${id}/pto-policies/`,
        updatePTOPolicy: (id: string, ptoId: string) => `/client/organizations/${id}/pto-policies/${ptoId}`,
        ptoRequests: (id: string) => `/client/organizations/${id}/paid-time-offs`,
        reviewPtoRequest: (id: string, requestId: string) => `/client/organizations/${id}/paid-time-offs/${requestId}/review`,
        holidays: (id: string) => `/client/organizations/${id}/holidays`,
        holiday: (id: string, holidayId: string) => `/client/organizations/${id}/holidays/${holidayId}`,
        workBreaks: (id: string) => `/client/organizations/${id}/work-breaks`,
        workBreak: (id: string, policyId: string) => `/client/organizations/${id}/work-breaks/${policyId}`,
        manualTimeRequests: (id: string) => `/client/organizations/${id}/manual-time-requests`,
        manualTimeRequestReview: (id: string, requestId: string) => `/client/organizations/${id}/manual-time-requests/${requestId}/review`,
        manualTimeRequestDirect: (id: string) => `/client/organizations/${id}/manual-time-requests/direct`,
    },
    projects: {
        index: "/client/projects",
        invite: "/invite", // Used as suffix
        me: "/projects/me",
        meInternal: "/internal/projects",
    },
    users: {
        index: "/users",
        meInternal: "/internal/users/me",
        meClient: "/client/users/me",
        meProfileInternal: "/internal/users/me/profile",
        meProfileClient: "/client/users/me/profile",
        meProfileImageClient: "/client/users/me/profile-image",
        meProfileImageInternal: "/internal/users/me/profile-image",
        meTwoFactorClient: "/client/users/me/two-factor",
        meTwoFactorInternal: "/internal/users/me/two-factor",
        mePasswordClient: "/client/users/me/password",
        mePasswordInternal: "/internal/users/me/password",
        internal: "/internal/users",
        internalResetPassword: (id: string) => `/internal/users/${id}/reset-password`,
        internalDisable: (id: string) => `/internal/users/${id}/disable`,
        internalRestore: (id: string) => `/internal/users/${id}/restore`,
        internalUpdate: (id: string) => `/internal/users/${id}`,
    },
    sessions: {
        index: "/sessions",
        aggregated: "/aggregated",
    },
    activityLogs: {
        latest: "/internal/activity-logs/latest",
        list: "/internal/activity-logs",
        organization: (organizationId: string) => `/client/organizations/${organizationId}/activity-logs`,
    },
    analytics: {
        stats: "/internal/analytics/stats",
    },
    dashboard: {
        overview: (organizationId: string) => `/client/organizations/${organizationId}/dashboard`,
    },
    rbac: {
        roles: "/internal/rbac/roles",
    },
    ai: {
        staff: "/client/ai/staff",
        org: "/client/ai/org",
        runUserInsights: "/client/ai/run-user-insights",
        insightsToReview: "/client/ai/insights-to-review",
        userProjectInsights: "/client/ai/user-project-insights",
        updateNotes: (insightId: string) => `/client/ai/notes/${insightId}`,
        triggerOrgNarrative: "/client/ai/trigger-org-narrative",
    },
    timesheets: {
        // memberTimesheets: (params?: any) => `/timesheets/member${params ? `?${new URLSearchParams(params)}` : ""}`,
        internalTimesheets: "/timesheets/member",
        sessions: (timesheetId: string) => `/timesheets/member/${timesheetId}/sessions`,
        timesheetDetail: (id: string) => `/internal/timesheets/${id}`,
        approveTimesheet: (id: string) => `/internal/timesheets/${id}/approve`,
        rejectTimesheet: (id: string) => `/internal/timesheets/${id}/reject`,
    },
    payments: {
        list: "/payments",
        process: "/payments/process",
        markPaid: (timesheetId: string) => `/payments/${timesheetId}/mark-paid`,
        markUnpaid: (timesheetId: string) => `/payments/${timesheetId}/mark-unpaid`,
        batches: "/payments/batch",
        batchDetail: (batchId: string) => `/payments/batch/${batchId}`,
        processBatch: (batchId: string) => `/payments/batch/${batchId}/process`,
    },
    paymentIntegrations: {
        index: "/client/payment-integrations",
        reveal: (organizationId: string, provider: string) => `/client/payment-integrations/reveal/${organizationId}/${provider}`,
    }
}
